name: diff
description: 'Run diff checks'
inputs:
  archivesspace_version:
    description: 'Production version of ArchivesSpace'
    required: true
    default: v3.3.1
  test_version:
    description: 'Test version of ArchivesSpace'
    required: true
    default: v3.3.1
runs:
  using: "composite"
  steps:
  - name: Set GitHub Path
    run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
    shell: bash
    env:
      GITHUB_ACTION_PATH: ${{ github.action_path }}

  - name: Checkout ArchivesSpace baseline repo
    env:
      PROD_ARCHIVESSPACE_VERSION: ${{ inputs.archivesspace_version }}
    uses: actions/checkout@v4
    with:
      ref: ${{ env.PROD_ARCHIVESSPACE_VERSION }}
      repository: Smithsonian/archivesspace
      path: archivesspace-baseline
      sparse-checkout: |
        frontend/app/views

  - name: Checkout ArchivesSpace repo
    env:
      PROD_ARCHIVESSPACE_VERSION: ${{ inputs.archivesspace_version }}
      TEST_VERSION: ${{ inputs.TEST_VERSION }}
    uses: actions/checkout@v4
    with:
      ref: ${{ env.PROD_ARCHIVESSPACE_VERSION }}
      repository: Smithsonian/archivesspace
      path: archivesspace
      sparse-checkout: |
        frontend/app/views

  - name: Diff with baseline
    id: baseline
    shell: bash
    run: |
      echo "baseline_changes=$(git diff --diff-filter=M --shortstat $GITHUB_ACTION_PATH/archivesspace-baseline/frontend/app/views $GITHUB_ACTION_PATH/plugin/frontend/views)" > $GITHUB_OUTPUT
  
  - name: Diff with new versions
    id: new
    shell: bash
    run: |
      echo "new_changes=$(git diff --diff-filter=M --shortstat ${{ github.workspace }}/archivesspace/frontend/app/views ${{ github.workspace }}/plugin/frontend/views)" > $GITHUB_OUTPUT

  - name: Diffs match
    id: matching
    shell: bash
    if: ${{ steps.baseline.outputs.baseline_changes == steps.new.outputs.new_changes }}
    run: |
      echo "${{ steps.baseline.outputs.baseline_changes }}"
      echo "${{ steps.new.outputs.new_changes }}"
      echo "${{ steps.new.outputs.new_changes2 }}"
      echo "All views overridden by this plugin match $PROD_ARCHIVESSPACE_VERSION of ArchivesSpace"

  - name: Diffs do not match
    id: not_matching
    shell: bash
    if: ${{ steps.baseline.outputs.baseline_changes != steps.new.outputs.new_changes }}
    run: |
      echo "Some views overridden by this plugin do not match those in ArchivesSpace ${{ matrix.archivesspace_version }}.  See:"
      echo "::set-output name=review_changes::$(git diff --diff-filter=M -w --color -- ${{ github.workspace }}/archivesspace/frontend/app/views ${{ github.workspace }}/plugin/frontend/views)"
      exit 1
