name: Build and deploy API docs

on:
  push:
    branches:
      - docs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: 'docs'

      - name: Build docs
        run: |
          npx @redocly/cli build-docs docs/openapi.yml

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: .
          force_orphan: true
          exclude_assets: '.github,backend,frontend,migrations,schemas'
