name: Diff views

on:
  pull_request:
    branches:
      - main
  push:

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.changed-views.outputs.views }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: changed-views
      with:
        filters: |
          views:
            - 'frontend/views/**'
    # run only if 'workflows' files were changed
    - name: run diff
      if: steps.changed-views.outputs.views == 'true'
      run: echo "Workflow file"

  diff:
    runs-on: ubuntu-latest
    # Wait from the paths-filter to be completed before starting next-job
    needs: paths-filter
    env:
      PROD_ARCHIVESSPACE_VERSION: v3.3.1
    continue-on-error: true
    strategy:
      matrix:
        archivesspace_version: [v3.3.1, v3.4.1, v3.5.1]
    steps:
    - name: Skip if unchanged
      if: needs.paths-filter.outputs.output1 != 'true'
      run: |
        exit 0

    - name: Checkout current plugin
      uses: actions/checkout@v4
      with:
        path: plugin
        sparse-checkout: |
          frontend/views

    - name: Checkout ArchivesSpace baseline repo
      uses: actions/checkout@v4
      with:
        ref: ${{ env.PROD_ARCHIVESSPACE_VERSION }}
        repository: Smithsonian/archivesspace
        path: archivesspace-baseline
        sparse-checkout: |
          frontend/app/views

    - name: Checkout ArchivesSpace repo
      uses: actions/checkout@v4
      with:
        ref: ${{ matrix.archivesspace_version }}
        repository: Smithsonian/archivesspace
        path: archivesspace
        sparse-checkout: |
          frontend/app/views

    - name: Diff with baseline
      id: baseline
      run: |
        echo "baseline_changes=$(git diff --diff-filter=M --shortstat ${{ github.workspace }}/archivesspace-baseline/frontend/app/views ${{ github.workspace }}/plugin/frontend/views)" > $GITHUB_OUTPUT
   
    - name: Diff with new versions
      id: new
      run: |
        echo "new_changes=$(git diff --diff-filter=M --shortstat ${{ github.workspace }}/archivesspace/frontend/app/views ${{ github.workspace }}/plugin/frontend/views)" > $GITHUB_OUTPUT

    - name: Diffs match
      if: ${{ steps.baseline.outputs.baseline_changes == steps.new.outputs.new_changes }}
      run: |
        echo "${{ steps.baseline.outputs.baseline_changes }}"
        echo "${{ steps.new.outputs.new_changes }}"
        echo "${{ steps.new.outputs.new_changes2 }}"
        echo "All views overridden by this plugin match $PROD_ARCHIVESSPACE_VERSION of ArchivesSpace"

    - name: Diffs do not match
      if: ${{ steps.baseline.outputs.baseline_changes != steps.new.outputs.new_changes }}
      run: |
        echo "Some views overridden by this plugin do not match those in ArchivesSpace ${{ matrix.archivesspace_version }}.  See:"
        echo "::set-output name=review_changes::$(git diff --diff-filter=M -w --color -- ${{ github.workspace }}/archivesspace/frontend/app/views ${{ github.workspace }}/plugin/frontend/views)"
        exit 1
